# Generated by Django 5.0.2 on 2024-02-16 22:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='funcionario_id',
            field=models.UUIDField(default=uuid.UUID('ab5d6144-5923-40eb-b338-96381ec2c733'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
