# Generated by Django 5.0.2 on 2024-02-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_funcionarios', '0002_alter_funcionario_funcionario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='funcionario_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
